### ISSUE TITLE
Chamber Temperature not showing up in Octoprint

### ISSUE THREAD

**Issue by WoodenNautilus** [synman/OctoPrint-MqttChamberTemperature#3]
Hello,

First of all, thank you for your work.

I am trying to use this plugin to retrieve temperature of a zigbee2mqtt sensor.

I have tested both the hostname and the topic using the mosquitto_sub utility. It works fine.

The MQTT plugin is also working fine, I tested it the same way.

The topic I want to use is called "zigbee2mqtt/Imprimante 3D".

I have enabled the debug logs for you plugin, whereas I only see logs from octoprint.plugins.mqtt.

The only log which is related to this topic is the following:
octoprint.util.comm - WARNING - Could not add custom temperature record C: C is a reserved identifier

Tell me if you need something else to analyze this topic.

Octoprint version: Version 1.9.3
MQTT plugin: 0.8.14
MQTT Chamber Temperature: 0.0.2

**Comment by WoodenNautilus** [comment]
I just had a look to the first issue and how you managed to solve it. I will try it and let you know if it fixes my issue.

**Comment by synman** [comment]
Two items from that other issue.  

* The base MQTT plug-in does not support spaces in topic names

* Be sure to enable Chamber in your printer profile

**Comment by WoodenNautilus** [comment]
It appears you were right. Sorry for bothering you. I also want to apologize for the duplicate topic.

**Comment by synman** [comment]
NP at all!
